lib/blog_web/router.ex
defmodule BlogWeb.Router do
  use BlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BlogWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BlogWeb do
    pipe_through :browser

    get "/", PageController, :index

    live "/posts", PostLive.Index, :index
    live "/posts/new", PostLive.Index, :new
    live "/posts/:id/edit", PostLive.Index, :edit

    live "/posts/:id", PostLive.Show, :show
    live "/posts/:id/show/edit", PostLive.Show, :edit

    live "/calculator", CalculatorLive.Index, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", BlogWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: BlogWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/blog_web/live/calculator_live/calculator_component.ex
defmodule BlogWeb.CalculatorComponent do
  use Phoenix.Component

  def number_button(assigns) do
    col_span =
      case Map.get(assigns, :col_span) do
        nil -> ""
        number -> "col-span-#{number}"
      end
    ~H"""
    <div phx-click="number" phx-value-number={assigns.number} class={"bg-blue-50 border border-gray-50 shadow rounded-lg p-2 h-12 #{col_span}"}><%= assigns.number %></div>
    """
  end

  def operation_button(assigns) do
    %{operation: operation, current_operation: current_operation} = assigns
    highlight =
      if (Map.get(assigns, :operation) == current_operation), do: "border-red-500"
    ~H"""
    <div phx-click="operation" phx-value-operation={operation} class={"bg-blue-50 border border-gray-50 shadow rounded-lg p-2 h-12 w-12 #{highlight}"}>
      <%= render_block(@inner_block) %>
    </div>
    """
  end
end

lib/blog_web/live/calculator_live/index.ex
defmodule BlogWeb.CalculatorLive.Index do
  use BlogWeb, :live_view
  import BlogWeb.CalculatorComponent

  def mount(_params, _session, socket) do
    {:ok, assign(socket, %{result: "0", operation: nil, refresh: false})}
  end

  def handle_event("calculate", %{"cal" => params}, socket) do
    IO.inspect params
    %{"first" => first, "second" => second} = params
    result = String.to_integer(first) + String.to_integer(second)
    {:noreply, assign(socket, :result, result)}
  end

  def handle_event("number", %{"number" => number}, socket) do
    result = socket.assigns.result
    case socket.assigns.refresh do
      true ->
        {:noreply, assign(socket, %{result: number, subject: result, refresh: false})}
      _ ->
        {:noreply, assign(socket, :result, add_digit(result, number))}
    end
  end

  defp add_digit(result, number) do
    case result do
      "0" -> number
      _ -> result <> number
    end
  end

  def handle_event("operation", %{"operation" => operation}, socket) do
    {:noreply, assign(socket, %{operation: operation, refresh: true})}
  end

  def handle_event("calculate", _params, socket) do
    %{subject: subject, result: mutate, operation: operation} = socket.assigns
    subject = String.to_integer(subject)
    mutate = String.to_integer(mutate)
    result =
      case operation do
        "/" ->
          div(subject, mutate)
        "*" ->
          subject * mutate
        "-" ->
          subject - mutate
        "+" ->
          subject + mutate
        _ ->
          "error"
      end
    {:noreply, assign(socket, %{result: result, operation: nil})}
  end
end

lib/blog_web/live/live_helpers.ex
defmodule BlogWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `BlogWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal BlogWeb.PostLive.FormComponent,
        id: @post.id || :new,
        action: @live_action,
        post: @post,
        return_to: Routes.post_index_path(@socket, :index) %>
  """
  def live_modal(component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(BlogWeb.ModalComponent, modal_opts)
  end
end

lib/blog_web/live/modal_component.ex
defmodule BlogWeb.ModalComponent do
  use BlogWeb, :live_component

  @impl true
  def render(assigns) do
    ~H"""
    <div
      id={@id}
      class="phx-modal"
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target={@myself}
      phx-page-loading>

      <div class="phx-modal-content">
        <%= live_patch raw("&times;"), to: @return_to, class: "phx-modal-close" %>
        <%= live_component @component, @opts %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

lib/blog_web/live/post_live/form_component.ex
defmodule BlogWeb.PostLive.FormComponent do
  use BlogWeb, :live_component

  alias Blog.Posts

  @impl true
  def update(%{post: post} = assigns, socket) do
    changeset = Posts.change_post(post)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"post" => post_params}, socket) do
    changeset =
      socket.assigns.post
      |> Posts.change_post(post_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"post" => post_params}, socket) do
    save_post(socket, socket.assigns.action, post_params)
  end

  defp save_post(socket, :edit, post_params) do
    case Posts.update_post(socket.assigns.post, post_params) do
      {:ok, _post} ->
        {:noreply,
         socket
         |> put_flash(:info, "Post updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_post(socket, :new, post_params) do
    case Posts.create_post(post_params) do
      {:ok, _post} ->
        {:noreply,
         socket
         |> put_flash(:info, "Post created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/blog_web/live/post_live/index.ex
defmodule BlogWeb.PostLive.Index do
  use BlogWeb, :live_view

  alias Blog.Posts
  alias Blog.Posts.Post

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :posts, list_posts())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Post")
    |> assign(:post, Posts.get_post!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Post")
    |> assign(:post, %Post{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Posts")
    |> assign(:post, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    post = Posts.get_post!(id)
    {:ok, _} = Posts.delete_post(post)

    {:noreply, assign(socket, :posts, list_posts())}
  end

  defp list_posts do
    Posts.list_posts()
  end
end

lib/blog_web/live/post_live/show.ex
defmodule BlogWeb.PostLive.Show do
  use BlogWeb, :live_view

  alias Blog.Posts

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:post, Posts.get_post!(id))}
  end

  defp page_title(:show), do: "Show Post"
  defp page_title(:edit), do: "Edit Post"
end

lib/blog_web/live/post_live/form_component.html.heex
<div>
  <h2><%= @title %></h2>

  <.form
    let={f}
    for={@changeset}
    id="post-form"
    phx-target={@myself}
    phx-change="validate"
    phx-submit="save">
  
    <%= label f, :title %>
    <%= text_input f, :title %>
    <%= error_tag f, :title %>
  
    <%= label f, :content %>
    <%= textarea f, :content %>
    <%= error_tag f, :content %>
  
    <div>
      <%= submit "Save", phx_disable_with: "Saving..." %>
    </div>
  </.form>
</div>

lib/blog_web/live/post_live/index.html.heex
<%= if @live_action in [:new, :edit] do %>
  <%= live_modal BlogWeb.PostLive.FormComponent,
    id: @post.id || :new,
    title: @page_title,
    action: @live_action,
    post: @post,
    return_to: Routes.post_index_path(@socket, :index) %>
<% end %>


<div class="flex flex-col">
  <div class="flex justify-end -mt-10 h-8 mb-2">
    <span class="inline-flex items-center px-4 py-2 shadow text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"><%= live_patch "New Post", to: Routes.post_index_path(@socket, :new) %></span>
  </div>
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Title
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Content
              </th>
              <th scope="col" class="relative px-6 py-3">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody id="posts" class="bg-white divide-y divide-gray-200">
            <%= for post <- @posts do %>
              <tr id={"post-#{post.id}"}>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                  <%= live_redirect post.title, to: Routes.post_show_path(@socket, :show, post) %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                  <%= post.content %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <span class="p-2 border broder-gray-50 rounded-lg"><%= live_redirect "🔍", to: Routes.post_show_path(@socket, :show, post) %></span>
                  <span class="p-2 border broder-gray-50 rounded-lg"><%= live_patch "✏️", to: Routes.post_index_path(@socket, :edit, post) %></span>
                  <span class="p-2 border broder-gray-50 rounded-lg"><%= link "🗑", to: "#", phx_click: "delete", phx_value_id: post.id, data: [confirm: "Are you sure?"] %></span>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

lib/blog_web/live/post_live/show.html.heex
<%= if @live_action in [:edit] do %>
  <%= live_modal BlogWeb.PostLive.FormComponent,
    id: @post.id,
    title: @page_title,
    action: @live_action,
    post: @post,
    return_to: Routes.post_show_path(@socket, :show, @post) %>
<% end %>

<article class="flex flex-col bg-white rounded-lg shadow">

  <div class="font-blod text-2xl bg-blue-100 rounded-t-lg p-4">
    <%= @post.title %>
  </div>

  <div class="p-4">
    <%= @post.content %>
  </div>
  <div class="flex justify-end space-x-2 m-4">
    <span class="p-2 border broder-gray-50 rounded-lg"><%= live_patch "✏️", to: Routes.post_show_path(@socket, :edit, @post) %></span>
    <span class="p-2 border broder-gray-50 rounded-lg"><%= live_redirect "🔙", to: Routes.post_index_path(@socket, :index) %></span>
  </div>

</article>